# Working with Numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 3, 4, 5, 6])
arr

array([1, 3, 4, 5, 6])

In [4]:
print(arr)

[1 3 4 5 6]


In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [6, 7, 8]], [[7, 8, 9], [4, 5, 6], [1, 2, 3]]])

arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]],

       [[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]])

In [9]:
print(arr_3d)

[[[1 2 3]
  [4 5 6]
  [6 7 8]]

 [[7 8 9]
  [4 5 6]
  [1 2 3]]]


In [10]:
arr_2d.shape

(2, 3)

In [11]:
arr_2d.size

6

In [12]:
arr_3d.shape

(2, 3, 3)

In [13]:
arr_3d.dtype

dtype('int32')

In [14]:
# Slicing and Indexing

new_arr = arr[1:4]

print(new_arr)

[3 4 5]


In [16]:
ele = arr_2d[1][1]

ele

5

# Array operations

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [20]:
ar_sum = arr1 + arr2
print(ar_sum)

[5 7 9]


In [21]:
arr_mul = arr1 * arr2

print(arr_mul)

[ 4 10 18]


In [23]:
print(arr1 * 5)

[ 5 10 15]


In [24]:
print(arr1 + 5)

[6 7 8]


In [26]:
# Matrix calculation

mat1 = np.array([[2, 3, 4], [4, 5, 6]])
mat2 = np.array([[1, 2, 3], [6, 7, 8]])


In [27]:
print(f'First Matrix:\n{mat1}')
print(f'Second Matrix:\n{mat2}')

First Matrix:
[[2 3 4]
 [4 5 6]]
Second Matrix:
[[1 2 3]
 [6 7 8]]


In [28]:
mat_add = mat1 + mat2
print(mat_add)

[[ 3  5  7]
 [10 12 14]]


In [29]:
# Subtraction

mat_sub = mat1 - mat2

print(mat_sub)

[[ 1  1  1]
 [-2 -2 -2]]


In [30]:
print(mat1 * 3)

[[ 6  9 12]
 [12 15 18]]


In [31]:
print(mat1 * mat2)

[[ 2  6 12]
 [24 35 48]]


In [33]:
print(np.dot(mat1, mat2))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [34]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[2, 3], [4, 5]])

print(np.dot(mat1, mat2))

[[10 13]
 [22 29]]


In [35]:
mat_mul = mat1 @ mat2

print(mat_mul)

[[10 13]
 [22 29]]


In [36]:
# Transpose

print(mat_mul.T)

[[10 22]
 [13 29]]


In [38]:
print(np.linalg.inv(mat_mul))

[[ 7.25 -3.25]
 [-5.5   2.5 ]]


In [39]:
print(np.linalg.det(mat1))

-2.0000000000000004


In [40]:
print(np.linalg.eig(mat1))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


# Vector calculation



In [41]:
v1 = np.array([1, 2, 3])
v2 = np.array([3, 4, 5])

print('v1 =', v1)
print('v2 =', v2)

v1 = [1 2 3]
v2 = [3 4 5]


In [42]:
dot_product = np.dot(v1, v2)
print(dot_product)

26


In [43]:
v1 @ v2

26

In [44]:
cross_product = np.cross(v1, v2)

print(cross_product)

[-2  4 -2]


In [45]:
'''
i j k
1 2 3
3 4 5

i (10 - 12) -j (5 - 9) + k (4 - 6)
-2i + 4j - 2k
[-2 4 -2]
'''

'\ni j k\n1 2 3\n3 4 5\n\ni (10 - 12) -j (5 - 9) + k (4 - 6)\n-2i + 4j - 2k\n[-2 4 -2]\n'

'''
# solve linear equation
2x + y = 5
x + y = 3

x = 2
y = 1
'''

In [46]:
# A * X = B
 # X = (A inv) B


In [50]:
A = np.array([[2, 1], [1, 1]])
B = np.array([5, 3])

X = np.linalg.solve(A, B)
print('Value of (x, y):', X)

Value of (x, y): [2. 1.]


In [51]:
np.random.randn(3, 3)

array([[-0.34107649, -0.11174425,  0.58169009],
       [-1.86923009, -1.57096112,  1.1896999 ],
       [ 1.32966473, -0.13508153, -0.34772663]])